name: add_policies.sh

on:
  push:
    branches:
      - 'release-*'

jobs:
  permissions: write-all
  add-policies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add policies
        run: |
          chmod +x .github/workflows/scripts/add_policies.sh
          bash .github/workflows/scripts/add_policies.sh ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Added policies to the release branch"
          git push
