name: Build and Test

on:
  push:
    branches: [master, dev]
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: corretto
      - name: Add execution privileges
        run: chmod +x ./mvnw
        working-directory: ./backend
      - name: Unit Test
        run: ./mvnw test
        working-directory: ./backend

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17.0.2
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - name: Add execution privileges
        run: chmod +x ./mvnw
        working-directory: ./backend
      - name: Build Backend .jar
        run: ./mvnw package
        working-directory: ./backend


  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Npm Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Npm Install
        run: npm install
        working-directory: ./frontend
      - name: Test frontend
        run: npm test
        working-directory: ./frontend

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Npm Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Npm Install
        run: npm install
        working-directory: ./frontend
      - name: Build Frontend
        run: CI='' npm run build
        working-directory: ./frontend

